VORTEX_PATH = $(realpath ../../../..)
GLSC_PATH = $(VORTEX_PATH)/glsc2
SRC_PATH = $(GLSC_PATH)/src 

UTILS_CL = $(wildcard ../utils/*.cl)
BACKEND_CL = $(wildcard ../*.cl)
HEADER_FILES = $(wildcard ../../*.h)
KERNELS_CL = $(wildcard *.cl)
KERNELS_O_C = $(KERNELS_CL:.cl=.o.c)

CL_FLAGS += -Werror -D__COMPILER_RELATIVE_PATH__ -I$(SRC_PATH) # -cl-nv-verbose
# OPT_FLAGS = -D'DEVICE_SUB_GROUP_SUPPORT=0' -D'DEVICE_IMAGE_SUPPORT=0'

.PHONY: all clean clean-all

CLC = $(GLSC_PATH)/src/compiler/clc 

%.o: %.cl $(UTILS_CL) $(BACKEND_CL) $(HEADER_FILES)
	$(CLC) $< $@ -DC_OPENCL_HOST $(CL_FLAGS) $(OPT_FLAGS)

%.o.c: %.o
	xxd -i $< > $@

all: $(KERNELS_O_C)

clean:
	rm -f *.o

clean-all: clean
	rm  -f *.o.c
