#ifndef CONSTANTS_DEVICE_H
#define CONSTANTS_DEVICE_H

#include "constants.h"
#include "config.device.h"

// -----------
// DEVICE CONSTANTS
// -----------
#define DEVICE_LOCAL_THREADS (1 << DEVICE_LOCAL_THREADS_LOG2)

#define DEVICE_SUB_GROUP_THREADS (1 << DEVICE_SUB_GROUP_THREADS_LOG2)
// ------
// RENDER CONFIG
// ------
#define CONF_ENABLED_SUBGROUPS
// ------
// KERNEL CONSTANTS
// ------
// Triangle Setup Configuration
#define CONS_SETUP_LOCAL_REQ_MEM                    (CONF_SETUP_BASE_LOCAL_REQ_MEM + (CONF_ENABLE_SUB_GROUPS_COMM ? CONF_SETUP_COMM_SUB_GROUP_REQ_MEM : CONF_SETUP_COMM_LOCAL_REQ_MEM))
#define CONS_SETUP_MAX_AVAILABLE_LOCAL_THREADS      MIN((DEVICE_LOCAL_MEM_SIZE / CONF_SETUP_LOCAL_REQ_MEM), DEVICE_LOCAL_THREADS)
#define CONS_SETUP_LOCAL_THREADS                    MIN(CONF_SETUP_MAX_AVAILABLE_LOCAL_THREADS, (1 << CONF_SETUP_MAX_LOCAL_THREADS_LOG2))

#if DEVICE_IMAGE_SUPPORT == 1
#define CONF_SETUP_IMAGE_ENABLED
#endif

#define CONF_SETUP_LOCAL_MEM_ENABLED

// Bin Raster Configuration
#if DEVICE_IMAGE_SUPPORT == 1
#define CONF_BIN_IMAGE_ENABLED
#endif

#define CONF_BIN_LOCAL_MEM_ENABLED

#if DEVICE_SUB_GROUP_SUPPORT == 1
#define CONF_BIN_SUB_GROUP_ENABLED
#endif

// Coarse Raster Configuration
#if DEVICE_IMAGE_SUPPORT == 1
#define CONF_COARSE_IMAGE_ENABLED
#endif

#define CONF_COARSE_LOCAL_MEM_ENABLED

#if DEVICE_SUB_GROUP_SUPPORT == 1
#define CONF_COARSE_SUB_GROUP_ENABLED
#endif

// Fine Raster Configuration
#if DEVICE_IMAGE_SUPPORT == 1
#define CONF_FINE_IMAGE_ENABLED
#endif

#define CONF_FINE_LOCAL_MEM_ENABLED

#if DEVICE_SUB_GROUP_SUPPORT == 1
#define CONF_FINE_SUB_GROUP_ENABLED
#endif

#if DEVICE_SUB_GROUP_RAW == 1
#define CONF_FINE_SUB_GROUP_RAW_ENABLED
#endif

#endif